### ISSUE TITLE
Close this fork and use "metafacture-lobid-plugin" instead 

### ISSUE THREAD

**Issue by dr0i** [hbz/metafacture-core#14]
We should use metafacture/metafacture-core directly. All lobid specific enhancements should be separated in a repository of its own.

**Comment by dr0i** [comment]
@fsteeg When https://github.com/hbz/lobid-resources/pull/1040 is closed , can we then close this repo, too?
Are there any other projects depending on this repo?

Also, have a look at the branches - anything we might want to use?
I see only https://github.com/hbz/metafacture-core/commit/dadf772982ac94c0754d1f2b34912ec2110be33e which is useful to log a concordance between internal SYS-ID and HT-IDs. Could be used in the lobid-resources repo overwriting the metafacture class.

**Comment by fsteeg** [comment]
> @fsteeg When hbz/lobid-resources#1040 is closed , can we then close this repo, too?
Are there any other projects depending on this repo?

Sounds good to me. To be on the save side, maybe we can make it read-only first? I think I've seen that somewhere.

> Also, have a look at the branches - anything we might want to use?
I see only dadf772 which is useful to log a concordance between internal SYS-ID and HT-IDs. Could be used in the lobid-resources repo overwriting the metafacture class.

Hm, the AlephHandler is currently final, and that's probably good. These changes are not in master it seems, so maybe you can cherry-pick them into a branch again? Or we could clean that debug code up  a bit (formatting, logger etc), and only run it if `log.isDebug()` (or something like that).

**Comment by dr0i** [comment]
Wait, @acka47 came up with a nice query revealing which projects depends on this repo: https://github.com/search?p=1&q=org%3Ahbz+git+clone+https%3A%2F%2Fgithub.com%2Fhbz%2Fmetafacture-core.git&type=Code. These projects have to be updated before this repo can be closed.

**Comment by acka47** [comment]
> Wait, @acka47 came up with a nice query revealing which projects depends on this repo: https://github.com/search?p=1&q=org%3Ahbz+git+clone+https%3A%2F%2Fgithub.com%2Fhbz%2Fmetafacture-core.git&type=Code. These projects have to be updated before this repo can be closed.

The query does not give back any results anymore. So I guess we can clode the issue? @dr0i please confirm and close the issue if correct.

**Comment by acka47** [comment]
We should probably also archive this repo, when the issue can be closed.
