### ISSUE TITLE
Duplicate data in arrays

### ISSUE THREAD

**Issue by SBRitter** [hbz/metafacture-core#9]
With the latest revision of this code, the transformation output of lobid-organisations exhibits multiple fields with duplicate data in arrays. This has probably something to do with 30ed8f339ddf0a659b0f4cc6e4ff420d31f9c1ec. It seems the merging of Sigel and Dbs data does not work properly anymore.

Sample output:
{
   "linkedTo":"http://lobid.org/organisation/DE-601",
   "rs":"110000000000",
   "subject":[
      "Recht",
      "Orientalistik",
      "Osteuropa",
      "Ostasien",
      "Afrika",
      "Amtsdruckschriften",
      "Handschriften",
      "Karten",
      "Geistes- und Sozialwissenschaften"
   ],
   "type":"Library",
   "ags":"11000000",
   "provides":"http://stabikat.de",
   "containedIn":"http://www.geonames.org/6547539",
   "isPrimaryTopicOf":[
      "http://dispatch.opac.d-nb.de/DB=1.2/CMD?ACT=SRCHA&IKT=8529&TRM=DE-1a",
      "http://dispatch.opac.d-nb.de/DB=1.2/CMD?ACT=SRCHA&IKT=8529&TRM=DE-1a"
   ],
   "wikipedia":[
      "http://de.wikipedia.org/wiki/Staatsbibliothek_zu_Berlin",
      "http://de.wikipedia.org/wiki/Staatsbibliothek_zu_Berlin"
   ],
   "id":"http://beta.lobid.org/organisations/DE-1a#!",
   "email":"mailto:info@sbb.spk-berlin.de",
   "address":{
      "addressLocality":"Berlin",
      "type":"http://schema.org/PostalAddress",
      "addressCountry":"DE",
      "postalCode":"10772"
   },
   "telephone":"0049 30 2 66-433888 (Auskunft)",
   "alternateName":[
      "SBB-PK, Potsdamer Straße",
      "Berlin SBB Haus Potsdamer Str"
   ],
   "classification":{
      "id":"http://purl.org/lobid/libtype#n11",
      "label":"Nationalbibliothek",
      "label_en":"National Library"
   },
   "@context":[
      "http://beta.lobid.org/organisations/context.jsonld",
      "http://beta.lobid.org/organisations/context.jsonld"
   ],
   "url":"http://www.staatsbibliothek-berlin.de",
   "stocksize":{
      "id":"http://purl.org/lobid/stocksize#n10",
      "label":"1.000.001 und mehr",
      "label_en":"1,000,001 and more"
   },
   "name":"Staatsbibliothek zu Berlin - Preußischer Kulturbesitz",
   "location":[
      {
         "type":"http://schema.org/Place",
         "address":{
            "postalCode":"10785",
            "streetAddress":"Potsdamer Str. 33",
            "addressLocality":"Berlin",
            "addressCountry":"DE",
            "type":"http://schema.org/PostalAddress"
         },
         "openingHoursSpecification":{
            "type":"http://schema.org/OpeningHoursSpecification",
            "comment":"Öffnungszeiten besonderer Bereiche s. Homepage",
            "description":"Mo-Fr 9.00-21.00, Sa 9.00-19.00"
         },
         "geo":{
            "lat":"52.50771",
            "lon":"13.37063"
         }
      }
   ],
   "isil":[
      "DE-1a",
      "DE-1a"
   ],
   "fundertype":{
      "id":"http://purl.org/lobid/fundertype#n07",
      "label":"Körperschaft oder Stiftung des öffentlichen Rechts",
      "label_en":"Corporate Body or Foundation under Public Law"
   },
   "dbsID":[
      "AK001",
      "AK001"
   ],
   "name_en":"Leibniz Institute for Zoo and Wildlife Research Berlin, Library",
   "sameAs":[
      "http://dbpedia.org/resource/Staatsbibliothek_zu_Berlin",
      "http://ld.zdb-services.de/resource/organisations/DE-1a"
   ]
}

**Comment by fsteeg** [comment]
Fixed by fcd30404b3c13bab06287563cbfdee11122a3bf9, see also https://github.com/culturegraph/metafacture-core/pull/198.
